### ISSUE TITLE
Failed tslint --project tsconfig.json in functions

### ISSUE THREAD

**Issue by ozelotjp** [ozelotjp/ShareWallet#1]
Error:
```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   '/app/functions',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@6.13.4
3 info using node@v10.19.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle functions@~prelint: functions@
6 info lifecycle functions@~lint: functions@
7 warn lifecycle The node binary used for scripts is /tmp/yarn--1586836869074-0.37680844808838687/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
8 verbose lifecycle functions@~lint: unsafe-perm in lifecycle true
9 verbose lifecycle functions@~lint: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/functions/node_modules/.bin:/tmp/yarn--1586836869074-0.37680844808838687:/app/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/usr/local/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/bin/node_modules/npm/bin/node-gyp-bin:/root/.vscode-server/bin/2aae1f26c72891c399f860409176fe435a154b13/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle functions@~lint: CWD: /app/functions
11 silly lifecycle functions@~lint: Args: [ '-c', 'tslint --project tsconfig.json' ]
12 silly lifecycle functions@~lint: Returned: code: 2  signal: null
13 info lifecycle functions@~lint: Failed to exec lint script
14 verbose stack Error: functions@ lint: `tslint --project tsconfig.json`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid functions@
16 verbose cwd /app
17 verbose Linux 4.19.76-linuxkit
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--prefix" "/app/functions" "run" "lint"
19 verbose node v10.19.0
20 verbose npm  v6.13.4
21 error code ELIFECYCLE
22 error errno 2
23 error functions@ lint: `tslint --project tsconfig.json`
23 error Exit status 2
24 error Failed at the functions@ lint script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 2, true ]
```

**Comment by ozelotjp** [comment]
Reason: after adding tslint to a dependency package, not run `npm i`
